# Generated by Django 3.0.8 on 2020-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_auto', models.CharField(default='', max_length=50)),
                ('model_auto', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=50)),
                ('lenght', models.CharField(default='', max_length=15)),
                ('height', models.CharField(default='', max_length=15)),
                ('width', models.CharField(default='', max_length=15)),
                ('clearance', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
