# Generated by Django 3.0.8 on 2020-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
